# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname landmarks_maxmin_cpp
#' @export
landmarks_maxmin_cpp <- function(x, n = 0L, eps = 0, seed_index = 0L) {
    .Call('_landmark_landmarks_maxmin_cpp', PACKAGE = 'landmark', x, n, eps, seed_index)
}

#' @rdname landmarks_lastfirst_cpp
#' @export
landmarks_lastfirst_cpp <- function(x, k, seed_index = 0L) {
    .Call('_landmark_landmarks_lastfirst_cpp', PACKAGE = 'landmark', x, k, seed_index)
}

#' @rdname landmarks_maxmin
#' @export
landmark_maxmin <- function(x, n, seed_index = 0L) {
    .Call('_landmark_landmark_maxmin', PACKAGE = 'landmark', x, n, seed_index)
}

