# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname landmarks_ball
#' @export
landmark_maxmin <- function(x, n, seed_index = 0L) {
    .Call('_landmark_landmark_maxmin', PACKAGE = 'landmark', x, n, seed_index)
}

