# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eccentricity <- function(from, x, type = 1L) {
    .Call('_maxmin_eccentricity', PACKAGE = 'maxmin', from, x, type)
}

landmark_maxmin <- function(x, n, seed = 0L) {
    .Call('_maxmin_landmark_maxmin', PACKAGE = 'maxmin', x, n, seed)
}

